### ISSUE TITLE
Topページのquotableタイトル「Maxim」のスマホ表示が崩れる件

### ISSUE THREAD

**Issue by moritanuki** [kip2/my-website#1]
### 概要
楽しい仕掛けがいっぱいのWebサイトだったので思わず見入ってしまいました...。
本件ですが、スマホだと画像のようにTOPページのみh1要素が右横にはみ出してしまっています。
（他のページでは同事象は見受けられず。コードも同様に他の `<h1>` で対策しているのは文字サイズだけの模様。）
![image](https://github.com/kip2/my-website/assets/82251856/6e34b9a0-6e0c-470f-be3c-d9c25654c212)

### 提案
レスポンシブ用にCSSを付けているように思えたんですが、意外と何も指定しない方がスッキリ収まる気がしました。
```typescript
<h1 className='mx-auto text-center text-5xl font-serif italic'>
    Maxim
</h1>
```

**Comment by kip2** [comment]
ご指摘ありがとうございます！
CSS難しい＆レスポンシブ難しすぎていつも枕を濡らしておりますので、ご指摘＆ご提案いただいてとても助かります！

さて、ご提案の修正内容で問題ないことを実地で確認しましたので、ご提案の内容を取り入れて本件クローズいたしました。

また、修正時に、コンポーネント名が画面表示の名前と異なっていることも見つけましたので、そちらも修正しました。
修正前：コンポーネント名「Quetes」 -> 画面表示「Maxim」
修正後：コンポーネント名「Maxim」 -> 画面表示「Maxim」
