### ISSUE TITLE
READMEのAbout this siteについて

### ISSUE THREAD

**Issue by Aki158** [kip2/my-website#3]
## 概要

すばらしいWebサイトの公開ありがとうございます！
本件ですが、READMEの記載について技術スタック表は、htmlのtableタグで書くことで、縦の要素をつなげられます。

## 提案
以下のソースコードを適用することで、イメージのような表が作成されます。

### ソースコード
```html
<table>
<tr>
  <th>ジャンル</th>
  <th>使用している技術</th>
</tr>
<tr>
  <td rowspan=3>フロントエンド</td>
  <td>TypeScript</td>
</tr>
<tr>
  <td>React.js</td>
</tr>
<tr>
  <td>TailwindCSS</td>
</tr>
<tr>
  <td rowspan=3>バックエンド</td>
  <td>AWS</td>
</tr>
<tr>
  <td>NGINX</td>
</tr>
<tr>
  <td>Docker</td>
</tr>
<tr>
  <td>その他</td>
  <td>ShellScript(zsh)</td>
</tr>
```

### イメージ
<table>
<tr>
  <th>ジャンル</th>
  <th>使用している技術</th>
</tr>
<tr>
  <td rowspan=3>フロントエンド</td>
  <td>TypeScript</td>
</tr>
<tr>
  <td>React.js</td>
</tr>
<tr>
  <td>TailwindCSS</td>
</tr>
<tr>
  <td rowspan=3>バックエンド</td>
  <td>AWS</td>
</tr>
<tr>
  <td>NGINX</td>
</tr>
<tr>
  <td>Docker</td>
</tr>
<tr>
  <td>その他</td>
  <td>ShellScript(zsh)</td>
</tr>

**Comment by kip2** [comment]
うわーい！Akiさんだ！
指摘助かります！

サイトの方の技術スタックではちゃんとまとめているのに、READMEではまとめ忘れてましたね...
感謝感謝

なお、ついでにbashの追加忘れに気づいていたので追加しています（サイト側の方は直ってないですが、それは別の修正と同時に上げる予定です）

**Comment by Aki158** [comment]
@kip2 さん

修正ありがとうございます！

フロントエンドに`使用している技術`が入ってます！
おそらく、`TypeScript`が正しいです。

![image](https://github.com/kip2/my-website/assets/119317071/fe0275ef-f81c-43d9-b9dc-338965055db4)

**Comment by kip2** [comment]
うひー！
めっちゃ恥ずかしい間違いしてるー！

ご指摘いただいたところ、直しました！
